// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoTietKiem.Data;

namespace SoTietKiem.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20191123193352_Initial_Migration")]
    partial class Initial_Migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SoTietKiem.Models.ChiTietSoTietKiem", b =>
                {
                    b.Property<int>("PhieuGuiRutTienId")
                        .HasColumnType("int");

                    b.Property<double?>("LaiSuat")
                        .HasColumnType("float");

                    b.Property<double?>("LaiSuatNgay")
                        .HasColumnType("float");

                    b.Property<double?>("LaiSuatThang")
                        .HasColumnType("float");

                    b.Property<int?>("LoaiTietKiemId")
                        .HasColumnType("int");

                    b.Property<int?>("Mskh")
                        .HasColumnName("MSKH")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayGui")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayRut")
                        .HasColumnType("datetime");

                    b.Property<string>("NghiepVu")
                        .HasColumnType("ntext");

                    b.Property<double?>("SoDuCuoiKy")
                        .HasColumnType("float");

                    b.Property<double?>("SoDuDauKy")
                        .HasColumnType("float");

                    b.Property<int?>("SoNgayLaiSuat")
                        .HasColumnType("int");

                    b.Property<int?>("SoThangLaiSuat")
                        .HasColumnType("int");

                    b.Property<double?>("SoTienGui")
                        .HasColumnType("float");

                    b.Property<double?>("SoTienRut")
                        .HasColumnType("float");

                    b.HasKey("PhieuGuiRutTienId");

                    b.ToTable("ChiTietSoTietKiem");
                });

            modelBuilder.Entity("SoTietKiem.Models.LoaiTietKiem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("KyHan")
                        .HasColumnType("int");

                    b.Property<double?>("LaiSuat")
                        .HasColumnType("float");

                    b.Property<int?>("LoaiTietKiem1")
                        .HasColumnName("LoaiTietKiem")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayHieuLuc")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("LoaiTietKiem");
                });

            modelBuilder.Entity("SoTietKiem.Models.PhieuGuiRutTien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KhachHang")
                        .HasColumnType("ntext");

                    b.Property<int?>("Mskh")
                        .HasColumnName("MSKH")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Ngay")
                        .HasColumnType("datetime");

                    b.Property<double?>("SoTien")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Mskh");

                    b.ToTable("PhieuGuiRutTien");
                });

            modelBuilder.Entity("SoTietKiem.Models.QuyDinh", b =>
                {
                    b.Property<int>("Msqd")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MSQD")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Ngay")
                        .HasColumnType("datetime");

                    b.Property<string>("NoiDung")
                        .HasColumnType("ntext");

                    b.HasKey("Msqd");

                    b.ToTable("QuyDinh");
                });

            modelBuilder.Entity("SoTietKiem.Models.SoTK", b =>
                {
                    b.Property<int>("Mskh")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MSKH")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cmnd")
                        .HasColumnName("CMND")
                        .HasColumnType("nvarchar(13)")
                        .HasMaxLength(13);

                    b.Property<string>("DiaChi")
                        .HasColumnType("ntext");

                    b.Property<string>("KhachHang")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("LoaiTietKiemId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayDongSo")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayMoSo")
                        .HasColumnType("datetime");

                    b.Property<double?>("SoDu")
                        .HasColumnType("float");

                    b.Property<double?>("SoTienGui")
                        .HasColumnType("float");

                    b.HasKey("Mskh");

                    b.HasIndex("LoaiTietKiemId");

                    b.ToTable("SoTK");
                });

            modelBuilder.Entity("SoTietKiem.Models.ChiTietSoTietKiem", b =>
                {
                    b.HasOne("SoTietKiem.Models.PhieuGuiRutTien", "PhieuGuiRutTien")
                        .WithOne("ChiTietSoTietKiem")
                        .HasForeignKey("SoTietKiem.Models.ChiTietSoTietKiem", "PhieuGuiRutTienId")
                        .HasConstraintName("FK_ChiTietSoTietKiem_PhieuGuiRutTien")
                        .IsRequired();
                });

            modelBuilder.Entity("SoTietKiem.Models.PhieuGuiRutTien", b =>
                {
                    b.HasOne("SoTietKiem.Models.SoTK", "MskhNavigation")
                        .WithMany("PhieuGuiRutTien")
                        .HasForeignKey("Mskh")
                        .HasConstraintName("FK_PhieuGuiRutTien_SoTietKiem");
                });

            modelBuilder.Entity("SoTietKiem.Models.SoTK", b =>
                {
                    b.HasOne("SoTietKiem.Models.LoaiTietKiem", "LoaiTietKiem")
                        .WithMany("SoTietKiem")
                        .HasForeignKey("LoaiTietKiemId")
                        .HasConstraintName("FK_SoTietKiem_LoaiTietKiem");
                });
#pragma warning restore 612, 618
        }
    }
}
